title:        Eli Duke
tagline:      ""
description:  ""
url:          http://www.eliduke.com
assets:       http://assets.eliduke.com
image:        http://assets.eliduke.com/layout/me-footer.jpg
author:
  name:       'Eli Duke'
  email:      'elimduke@gmail.com'
markdown:     kramdown
permalink:    pretty
highlighter:  rouge
collections:
  photography:
    output: true
    permalink: /photography/:path/
  recipes:
    output: true
    permalink: /recipes/:path/