title:        Eli Duke
tagline:      ""
description:  ""
url:          http://eliduke.com
assets:       http://assets.eliduke.com
author:
  name:       'Eli Duke'
  email:      'elimduke@gmail.com'
markdown:     rdiscount
permalink:    pretty
highlighter:  pygments
collections:
  photography:
    output: true
    permalink: /photography/:path/
  recipes:
    output: true
    permalink: /recipes/:path/