title:        Eli Duke
tagline:      ""
description:  ""
url:          https://eliduke.com
assets:       https://assets.eliduke.com
image:        https://assets.eliduke.com/layout/me-footer.jpg
author:
  name:       'Eli Duke'
  email:      'elimduke@gmail.com'
markdown:     kramdown
permalink:    pretty
highlighter:  rouge
collections:
  photography:
    output: true
    permalink: /photography/:path/
  recipes:
    output: true
    permalink: /recipes/:path/
